<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>e5ff1074-102b-4663-8570-49f7a2196ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Đăng nhập')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84ba8717-88a2-4855-8e08-868d16546110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/webdulich/user/login</value>
      <webElementGuid>0c3da11a-4cc9-42cd-9546-5720aab74586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>8c8b3844-2032-4d78-9267-92599655b6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;admin&quot;]/p[1]/a[1]</value>
      <webElementGuid>bb2e0730-e64e-4096-bd9f-2de4ab79d956</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng nhập')]</value>
      <webElementGuid>61816004-7fbc-41dd-a88d-b74492a5a252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DU LỊCH VIỆT NAM'])[1]/preceding::a[1]</value>
      <webElementGuid>dfbd66b9-13d9-4378-ae9c-4471dcf8b18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trang chủ'])[1]/preceding::a[1]</value>
      <webElementGuid>ccce5f0e-d9df-4f1a-b1ff-e57792d80adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng nhập']/parent::*</value>
      <webElementGuid>c4ea85d6-4b7e-49e6-855f-06bc05ea3376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/webdulich/user/login')]</value>
      <webElementGuid>c9b0527a-abc2-43df-bdbd-6c7be1ba6836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>acb3df15-2d6a-4267-bcf2-d730f1e74ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/webdulich/user/login' and (text() = 'Đăng nhập' or . = 'Đăng nhập')]</value>
      <webElementGuid>44d99c15-8c43-46fa-95de-09ce5c0c0eca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
