<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xc nhn t tour</name>
   <tag></tag>
   <elementGuidId>6fde6398-c6c9-4222-951e-8a90f91c47d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.luxury-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' luxury-btn ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad5d83af-4cf9-4680-8a1e-dfd3893c5bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bfa7ac9b-cad7-45cf-b802-2e3750622e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>luxury-btn</value>
      <webElementGuid>3f420aa4-c1bd-45c2-969f-4ab90d88249a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xác nhận đặt tour</value>
      <webElementGuid>9fadc8ff-b6cf-42f3-9898-cf628d7a7c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-68a4d3b16b18b832991f6f001a0887ea</value>
      <webElementGuid>85fb4edd-3c43-43cb-b591-94df5c714174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' luxury-btn ')]</value>
      <webElementGuid>e8a5fc1e-d0a5-4391-a852-5c8a4527e329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' luxury-btn ')]</value>
      <webElementGuid>b60635dc-8505-4221-a36e-a4a2c21313f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Xác nhận đặt tour' or . = 'Xác nhận đặt tour')]</value>
      <webElementGuid>cdd9b5bf-a342-4b68-ad33-9dbdfdbfa9c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
