<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AnhTour</name>
   <tag></tag>
   <elementGuidId>c052413a-aa5e-4332-b28b-a8413f2b4325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'file' and @name = 'AnhTour[]']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'AnhTour[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;AnhTour\[\]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;AnhTour\[\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f94560d2-8080-4411-a622-0d8b9f826b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>4a5b8900-b1cf-44ed-93c2-49e101dcfea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnhTour[]</value>
      <webElementGuid>7a5f03a7-ab6c-440e-9243-dd4d6b2b163f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>9eee2c3a-44dd-4ad6-a76a-97e2d2a3beb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6d8cd106-5e9a-44ff-80bb-831194a81b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-93c7f422c28e447343fd808d4c545751</value>
      <webElementGuid>989cfe42-9f88-4f09-8f84-0639c08ee908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'AnhTour[]']</value>
      <webElementGuid>db4a008c-f90d-4d98-ad43-cc1d3c7dfd42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'AnhTour[]']</value>
      <webElementGuid>0cb1eab5-4f8b-4a2f-81aa-3bd094f9fe8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'AnhTour[]']</value>
      <webElementGuid>85e932cf-3029-409b-b63e-48cfb8a78c68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
